# Generated by Django 5.0.2 on 2026-02-11 19:22

import diagnostics.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='السنة الدراسية')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=False, verbose_name='السنة النشطة')),
                ('code', models.CharField(editable=False, max_length=10, unique=True, verbose_name='كود السنة')),
            ],
            options={
                'verbose_name': 'سنة دراسية',
                'verbose_name_plural': 'السنوات الدراسية',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='اسم الملف')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='كود الملف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'تصنيف دليل',
                'verbose_name_plural': 'تصنيفات الأدلة',
            },
        ),
        migrations.CreateModel(
            name='OperationalGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='مؤشر الأداء / الهدف التشغيلي')),
                ('indicator_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم المؤشر')),
                ('code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='كود المؤشر')),
            ],
            options={
                'verbose_name': 'هدف تشغيلي / مؤشر',
                'verbose_name_plural': 'الأهداف التشغيلية / المؤشرات',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_no', models.TextField(unique=True, verbose_name='الرقم الشخصي (QID)')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم الطالب (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الطالب (إنجليزي)')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('grade', models.CharField(db_index=True, max_length=10, verbose_name='الصف')),
                ('section', models.CharField(db_index=True, max_length=10, verbose_name='الشعبة')),
                ('needs', models.CharField(blank=True, max_length=50, null=True, verbose_name='احتياجات خاصة')),
                ('parent_national_no', models.TextField(blank=True, null=True, verbose_name='رقم ولي الأمر الشخصي')),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم ولي الأمر')),
                ('parent_relation', models.CharField(blank=True, max_length=50, null=True, verbose_name='صلة القرابة')),
                ('parent_phone', models.TextField(blank=True, null=True, verbose_name='رقم هاتف ولي الأمر')),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='بريد ولي الأمر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'ordering': ['grade', 'section', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='اسم اللجنة')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='كود اللجنة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostics.academicyear')),
                ('members', models.ManyToManyField(blank=True, related_name='committees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لجنة',
                'verbose_name_plural': 'اللجان',
            },
        ),
        migrations.CreateModel(
            name='EvidenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الملف')),
                ('file', models.FileField(upload_to=diagnostics.models.get_evidence_upload_path, verbose_name='الملف')),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='اسم الملف الأصلي')),
                ('file_size', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='حجم الملف (بايت)')),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='بصمة الملف (SHA-256)')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='الوسوم (Tags)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostics.academicyear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_evidence_files', to=settings.AUTH_USER_MODEL)),
                ('evidence_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='diagnostics.evidencefile')),
            ],
            options={
                'verbose_name': 'وثيقة دليل',
                'verbose_name_plural': 'مستودع الأدلة',
            },
        ),
        migrations.CreateModel(
            name='GroupExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis1_name', models.CharField(blank=True, default='المحور الأول', max_length=255, verbose_name='اسم المحور 1')),
                ('axis2_name', models.CharField(blank=True, default='المحور الثاني', max_length=255, verbose_name='اسم المحور 2')),
                ('axis3_name', models.CharField(blank=True, default='المحور الثالث', max_length=255, verbose_name='اسم المحور 3')),
                ('axis4_name', models.CharField(blank=True, default='المحور الرابع', max_length=255, verbose_name='اسم المحور 4')),
                ('axis5_name', models.CharField(blank=True, default='المحور الخامس', max_length=255, verbose_name='اسم المحور 5')),
                ('axis6_name', models.CharField(blank=True, default='المحور السادس', max_length=255, verbose_name='اسم المحور 6')),
                ('axis1_evaluators', models.ManyToManyField(blank=True, related_name='axis1_groups', to=settings.AUTH_USER_MODEL, verbose_name='مقيّمين محور 1')),
                ('axis2_evaluators', models.ManyToManyField(blank=True, related_name='axis2_groups', to=settings.AUTH_USER_MODEL, verbose_name='مقيّمين محور 2')),
                ('axis3_evaluators', models.ManyToManyField(blank=True, related_name='axis3_groups', to=settings.AUTH_USER_MODEL, verbose_name='مقيّمين محور 3')),
                ('axis4_evaluators', models.ManyToManyField(blank=True, related_name='axis4_groups', to=settings.AUTH_USER_MODEL, verbose_name='مقيّمين محور 4')),
                ('axis5_evaluators', models.ManyToManyField(blank=True, related_name='axis5_groups', to=settings.AUTH_USER_MODEL, verbose_name='مقيّمين محور 5')),
                ('axis6_evaluators', models.ManyToManyField(blank=True, related_name='axis6_groups', to=settings.AUTH_USER_MODEL, verbose_name='مقيّمين محور 6')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='المسمى الوظيفي')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='كود المسمى')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_canonical', models.BooleanField(default=False, verbose_name='مسمى معتمد/رئيسي')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث')),
                ('groups', models.ManyToManyField(blank=True, related_name='job_titles', to='auth.group', verbose_name='مجموعات الصلاحيات')),
            ],
            options={
                'verbose_name': 'مسمى وظيفي',
                'verbose_name_plural': 'المسميات الوظيفية',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='الاسم')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='كود الموظف الهيكلي')),
                ('nationality', models.CharField(choices=[('QA', 'قطري'), ('EXP', 'مقيم')], db_index=True, default='EXP', max_length=10, verbose_name='الجنسية')),
                ('job_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='الرقم الوظيفي')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='البريد الإلكتروني')),
                ('national_no', models.TextField(blank=True, null=True, unique=True, verbose_name='الرقم الوطني')),
                ('phone_no', models.TextField(blank=True, null=True, verbose_name='رقم الجوال')),
                ('account_no', models.TextField(blank=True, null=True, verbose_name='رقم الحساب')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='diagnostics.jobtitle')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
            },
        ),
        migrations.CreateModel(
            name='StrategicGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='الهدف الاستراتيجي')),
                ('goal_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهدف')),
                ('code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='كود الهدف')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_goals', to='diagnostics.academicyear')),
            ],
            options={
                'verbose_name': 'هدف استراتيجي',
                'verbose_name_plural': 'الأهداف الاستراتيجية',
            },
        ),
        migrations.CreateModel(
            name='OperationalPlanItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='المجال')),
                ('procedure', models.TextField(blank=True, null=True, verbose_name='الإجراء التنفيذي')),
                ('code', models.CharField(editable=False, max_length=50, null=True, unique=True, verbose_name='كود الإجراء الذكي')),
                ('executor', models.CharField(blank=True, max_length=255, null=True, verbose_name='الجهة المنفذة (نصي)')),
                ('date_range', models.CharField(blank=True, max_length=255, null=True, verbose_name='فترة التنفيذ')),
                ('follow_up', models.CharField(blank=True, max_length=255, null=True, verbose_name='حالة المتابعة')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='الملاحظات والتحديات')),
                ('evidence_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الدليل')),
                ('evidence_source_employee', models.CharField(blank=True, max_length=255, null=True, verbose_name='المقيّم')),
                ('evidence_source_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='موقع الدليل (نصي)')),
                ('evaluation', models.CharField(blank=True, max_length=255, null=True, verbose_name='التقييم')),
                ('evaluation_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات التقييم')),
                ('evidence_requested', models.BooleanField(default=False, verbose_name='طلب دليل؟')),
                ('evidence_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ طلب الدليل')),
                ('evidence_request_note', models.TextField(blank=True, null=True, verbose_name='ملاحظة طلب الدليل')),
                ('last_review_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر مراجعة')),
                ('digital_seal', models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='بصمة النزاهة الرقمية')),
                ('status', models.CharField(blank=True, choices=[('Draft', 'مسودة'), ('In Progress', 'جاري التنفيذ'), ('Pending Review', 'بانتظار المراجعة'), ('Completed', 'مكتمل'), ('Returned', 'مرفوض')], db_index=True, default='In Progress', max_length=50, null=True, verbose_name='حالة البند')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث')),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='diagnostics.academicyear')),
                ('evaluator_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_plan_items', to='diagnostics.committee', verbose_name='اللجنة المقيمة')),
                ('evidence_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_plan_items', to='diagnostics.evidencedocument')),
                ('executor_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_plan_items', to='diagnostics.committee', verbose_name='اللجنة المنفذة')),
                ('operational_goal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostics.operationalgoal')),
                ('strategic_goal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostics.strategicgoal')),
            ],
            options={
                'verbose_name': 'بند خطة تشغيلية',
                'verbose_name_plural': 'بنود الخطة التشغيلية',
            },
        ),
        migrations.AddField(
            model_name='operationalgoal',
            name='strategic_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_goals', to='diagnostics.strategicgoal'),
        ),
    ]
