# Generated by Django 6.0.2 on 2026-02-06 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم الملف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الملف')),
            ],
            options={
                'verbose_name': 'ملف دليل',
                'verbose_name_plural': 'ملفات الأدلة',
                'db_table': 'evidence_files',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='المسمى الوظيفي')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'مسمى وظيفي',
                'verbose_name_plural': 'المسميات الوظيفية',
                'db_table': 'job_titles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم اللجنة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('members', models.ManyToManyField(blank=True, related_name='committees', to=settings.AUTH_USER_MODEL, verbose_name='الأعضاء')),
            ],
            options={
                'verbose_name': 'لجنة',
                'verbose_name_plural': 'اللجان',
                'db_table': 'committees',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OperationalPlanItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='السنة')),
                ('rank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='المجال')),
                ('target', models.TextField(blank=True, null=True, verbose_name='الهدف الاستراتيجي')),
                ('indicator', models.TextField(blank=True, null=True, verbose_name='مؤشر الأداء')),
                ('procedure', models.TextField(blank=True, null=True, verbose_name='الإجراء التنفيذي')),
                ('executor', models.CharField(blank=True, max_length=255, null=True, verbose_name='الجهة المنفذة (نصي)')),
                ('date_range', models.CharField(blank=True, max_length=255, null=True, verbose_name='فترة التنفيذ')),
                ('follow_up', models.CharField(blank=True, max_length=255, null=True, verbose_name='حالة المتابعة')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='الملاحظات والتحديات')),
                ('evidence_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الدليل')),
                ('evidence_source_employee', models.CharField(blank=True, max_length=255, null=True, verbose_name='المقيّم')),
                ('evidence_source_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='موقع الدليل (الملف)')),
                ('evaluation', models.CharField(blank=True, max_length=255, null=True, verbose_name='التقييم')),
                ('evaluation_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات التقييم')),
                ('status', models.CharField(blank=True, choices=[('Draft', 'مسودة'), ('In Progress', 'جاري التنفيذ'), ('Pending Review', 'بانتظار المراجعة'), ('Completed', 'مكتمل'), ('Returned', 'مرفوض')], default='In Progress', max_length=50, null=True, verbose_name='حالة البند')),
                ('evaluator_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_plan_items', to='coredata.committee', verbose_name='اللجنة المقيمة')),
                ('executor_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_plan_items', to='coredata.committee', verbose_name='اللجنة المنفذة')),
            ],
            options={
                'verbose_name': 'بند خطة تشغيلية',
                'verbose_name_plural': 'بنود الخطة التشغيلية',
                'db_table': 'operational_plan_items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('job_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='الرقم الوظيفي')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='البريد الإلكتروني')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='coredata.jobtitle', verbose_name='المسمى الوظيفي')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
                'db_table': 'staff',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True, verbose_name='صلاحية العرض')),
                ('evidence_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permitted_jobs', to='coredata.evidencefile', verbose_name='الملف')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_permissions', to='coredata.jobtitle', verbose_name='المسمى الوظيفي')),
            ],
            options={
                'verbose_name': 'صلاحية ملف',
                'verbose_name_plural': 'صلاحيات الملفات',
                'db_table': 'file_permissions',
                'managed': True,
                'unique_together': {('job_title', 'evidence_file')},
            },
        ),
    ]
