# Generated by Django 6.0.2 on 2026-02-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalplanitems',
            name='indicator_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم المؤشر'),
        ),
        migrations.AddField(
            model_name='operationalplanitems',
            name='procedure_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الإجراء'),
        ),
        migrations.AddField(
            model_name='operationalplanitems',
            name='target_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهدف'),
        ),
    ]
