# Generated by Django 6.0.2 on 2026-02-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0002_operationalplanitems_indicator_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='national_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='الرقم الوطني'),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال'),
        ),
    ]
