# Generated by Django 6.0.2 on 2026-02-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0003_staff_national_no_staff_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='كود اللجنة'),
        ),
        migrations.AddField(
            model_name='evidencefile',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='كود الملف'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='كود المسمى'),
        ),
        migrations.AddField(
            model_name='staff',
            name='account_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الحساب'),
        ),
    ]
