# Generated by Django 6.0.2 on 2026-02-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0004_committee_code_evidencefile_code_jobtitle_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='committee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='evidencefile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='evidencefile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='filepermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='filepermission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='operationalplanitems',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='operationalplanitems',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='staff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='كود اللجنة'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='اسم اللجنة'),
        ),
        migrations.AlterField(
            model_name='evidencefile',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='كود الملف'),
        ),
        migrations.AlterField(
            model_name='evidencefile',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='اسم الملف'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='كود المسمى'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='operationalplanitems',
            name='evaluation',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='operationalplanitems',
            name='executor',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='الجهة المنفذة (نصي)'),
        ),
        migrations.AlterField(
            model_name='operationalplanitems',
            name='follow_up',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='حالة المتابعة'),
        ),
        migrations.AlterField(
            model_name='operationalplanitems',
            name='indicator_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='رقم المؤشر'),
        ),
        migrations.AlterField(
            model_name='operationalplanitems',
            name='procedure_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='رقم الإجراء'),
        ),
        migrations.AlterField(
            model_name='operationalplanitems',
            name='rank_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='المجال'),
        ),
        migrations.AlterField(
            model_name='operationalplanitems',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'مسودة'), ('In Progress', 'جاري التنفيذ'), ('Pending Review', 'بانتظار المراجعة'), ('Completed', 'مكتمل'), ('Returned', 'مرفوض')], db_index=True, default='In Progress', max_length=50, null=True, verbose_name='حالة البند'),
        ),
        migrations.AlterField(
            model_name='operationalplanitems',
            name='target_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='رقم الهدف'),
        ),
        migrations.AlterField(
            model_name='operationalplanitems',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='السنة'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='account_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='رقم الحساب'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='job_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='الرقم الوظيفي'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='national_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='الرقم الوطني'),
        ),
    ]
