# Generated by Django 6.0.2 on 2026-02-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0006_alter_staff_user'),
        ('project_memory', '0006_alter_actionplanitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='strategic_goals',
            field=models.ManyToManyField(blank=True, related_name='responsible_committees', to='project_memory.projectgoal', verbose_name='الأهداف الاستراتيجية المرتبطة'),
        ),
        migrations.AddField(
            model_name='operationalplanitems',
            name='last_review_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر مراجعة'),
        ),
    ]
