# Generated by Django 6.0.2 on 2026-02-07 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0007_committee_strategic_goals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: 2025-2026', max_length=20, unique=True, verbose_name='السنة الدراسية')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=False, verbose_name='السنة النشطة')),
                ('code', models.CharField(editable=False, max_length=10, unique=True, verbose_name='كود السنة')),
            ],
            options={
                'verbose_name': 'سنة دراسية',
                'verbose_name_plural': 'السنوات الدراسية',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='OperationalGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='مؤشر الأداء / الهدف التشغيلي')),
                ('indicator_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم المؤشر')),
                ('code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='كود المؤشر')),
            ],
            options={
                'verbose_name': 'هدف تشغيلي / مؤشر',
                'verbose_name_plural': 'الأهداف التشغيلية / المؤشرات',
            },
        ),
        migrations.RenameField(
            model_name='committee',
            old_name='strategic_goals',
            new_name='strategic_goals_link',
        ),
        migrations.AddField(
            model_name='operationalplanitems',
            name='code',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True, verbose_name='كود الإجراء الذكي'),
        ),
        migrations.AlterField(
            model_name='operationalplanitems',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='السنة (قديم)'),
        ),
        migrations.AddField(
            model_name='committee',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.academicyear', verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='operationalplanitems',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='coredata.academicyear', verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='operationalplanitems',
            name='operational_goal_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.operationalgoal', verbose_name='الهدف التشغيلي / المؤشر'),
        ),
        migrations.CreateModel(
            name='StrategicGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='الهدف الاستراتيجي')),
                ('goal_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهدف')),
                ('code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='كود الهدف')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_goals', to='coredata.academicyear', verbose_name='السنة الدراسية')),
            ],
            options={
                'verbose_name': 'هدف استراتيجي',
                'verbose_name_plural': 'الأهداف الاستراتيجية',
            },
        ),
        migrations.AddField(
            model_name='operationalgoal',
            name='strategic_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_goals', to='coredata.strategicgoal', verbose_name='الهدف الاستراتيجي'),
        ),
        migrations.AddField(
            model_name='operationalplanitems',
            name='strategic_goal_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.strategicgoal', verbose_name='الهدف الاستراتيجي المرتبط'),
        ),
    ]
