# Generated by Django 6.0.2 on 2026-02-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0008_academicyear_operationalgoal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='كود الموظف الهيكلي'),
        ),
        migrations.AddField(
            model_name='staff',
            name='nationality',
            field=models.CharField(choices=[('QA', 'قطري'), ('EXP', 'مقيم')], db_index=True, default='EXP', max_length=10, verbose_name='الجنسية'),
        ),
    ]
