# Generated by Django 6.0.2 on 2026-02-07 09:10

import coredata.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0010_operationalplanitems_digital_seal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstaff',
            name='account_no',
            field=coredata.models.EncryptedCharField(blank=True, null=True, verbose_name='رقم الحساب'),
        ),
        migrations.AlterField(
            model_name='historicalstaff',
            name='national_no',
            field=coredata.models.EncryptedCharField(blank=True, db_index=True, null=True, verbose_name='الرقم الوطني'),
        ),
        migrations.AlterField(
            model_name='historicalstaff',
            name='phone_no',
            field=coredata.models.EncryptedCharField(blank=True, null=True, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='account_no',
            field=coredata.models.EncryptedCharField(blank=True, null=True, verbose_name='رقم الحساب'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='national_no',
            field=coredata.models.EncryptedCharField(blank=True, null=True, unique=True, verbose_name='الرقم الوطني'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_no',
            field=coredata.models.EncryptedCharField(blank=True, null=True, verbose_name='رقم الجوال'),
        ),
    ]
