# Generated by Django 6.0.2 on 2026-02-07 11:43

import coredata.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0011_alter_historicalstaff_account_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_no', coredata.models.EncryptedCharField(unique=True, verbose_name='الرقم الشخصي (QID)')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم الطالب (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الطالب (إنجليزي)')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('grade', models.CharField(db_index=True, max_length=10, verbose_name='الصف')),
                ('section', models.CharField(db_index=True, max_length=10, verbose_name='الشعبة')),
                ('needs', models.CharField(blank=True, max_length=50, null=True, verbose_name='احتياجات خاصة')),
                ('parent_national_no', coredata.models.EncryptedCharField(blank=True, null=True, verbose_name='رقم ولي الأمر الشخصي')),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم ولي الأمر')),
                ('parent_relation', models.CharField(blank=True, max_length=50, null=True, verbose_name='صلة القرابة')),
                ('parent_phone', coredata.models.EncryptedCharField(blank=True, null=True, verbose_name='رقم هاتف ولي الأمر')),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='بريد ولي الأمر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'db_table': 'students',
                'ordering': ['grade', 'section', 'name_ar'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalStudent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('national_no', coredata.models.EncryptedCharField(db_index=True, verbose_name='الرقم الشخصي (QID)')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم الطالب (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الطالب (إنجليزي)')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('grade', models.CharField(db_index=True, max_length=10, verbose_name='الصف')),
                ('section', models.CharField(db_index=True, max_length=10, verbose_name='الشعبة')),
                ('needs', models.CharField(blank=True, max_length=50, null=True, verbose_name='احتياجات خاصة')),
                ('parent_national_no', coredata.models.EncryptedCharField(blank=True, null=True, verbose_name='رقم ولي الأمر الشخصي')),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم ولي الأمر')),
                ('parent_relation', models.CharField(blank=True, max_length=50, null=True, verbose_name='صلة القرابة')),
                ('parent_phone', coredata.models.EncryptedCharField(blank=True, null=True, verbose_name='رقم هاتف ولي الأمر')),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='بريد ولي الأمر')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='آخر تحديث')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical طالب',
                'verbose_name_plural': 'historical الطلاب',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
