# Generated by Django 5.0 on 2026-02-08 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0012_student_historicalstudent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الملف')),
                ('file', models.FileField(upload_to='evidence_docs/%Y/%m/', verbose_name='الملف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coredata.academicyear', verbose_name='السنة الدراسية')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_evidence_files', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'وثيقة دليل',
                'verbose_name_plural': 'مستودع الأدلة',
                'db_table': 'evidence_documents',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='operationalplanitems',
            name='evidence_document',
            field=models.ForeignKey(blank=True, help_text='اختر ملفاً من مستودع ملفاتك', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_plan_items', to='coredata.evidencedocument', verbose_name='ملف الدليل المرفق'),
        ),
        migrations.AddField(
            model_name='historicaloperationalplanitems',
            name='evidence_document',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='اختر ملفاً من مستودع ملفاتك', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='coredata.evidencedocument', verbose_name='ملف الدليل المرفق'),
        ),
    ]