# Generated by Django 5.0 on 2026-02-08 10:30

import coredata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0013_evidence_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencedocument',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='بصمة الملف (SHA-256)'),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='حجم الملف (بايت)'),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='original_filename',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='اسم الملف الأصلي'),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='tags',
            field=models.CharField(blank=True, help_text='كلمات مفتاحية مفصولة بفاصلة لسهولة البحث', max_length=255, null=True, verbose_name='الوسوم (Tags)'),
        ),
        migrations.AlterField(
            model_name='evidencedocument',
            name='file',
            field=models.FileField(upload_to=coredata.models.get_evidence_upload_path, verbose_name='الملف'),
        ),
    ]