# Generated by Django 5.0 on 2026-02-08 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0014_evidence_document_enhancement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidencefile',
            options={'managed': True, 'verbose_name': 'تصنيف دليل', 'verbose_name_plural': 'تصنيفات الأدلة'},
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='evidence_type',
            field=models.ForeignKey(blank=True, help_text='اختر نوع الملف (مثلاً: سجل حضور، خطة أسبوعية...)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='coredata.evidencefile', verbose_name='تصنيف الدليل'),
        ),
    ]