# Generated by Django 6.0.2 on 2026-02-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0015_evidence_document_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalevidencefile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical تصنيف دليل', 'verbose_name_plural': 'historical تصنيفات الأدلة'},
        ),
        migrations.AddField(
            model_name='historicaloperationalplanitems',
            name='evidence_request_note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظة طلب الدليل'),
        ),
        migrations.AddField(
            model_name='historicaloperationalplanitems',
            name='evidence_requested',
            field=models.BooleanField(default=False, verbose_name='طلب دليل؟'),
        ),
        migrations.AddField(
            model_name='historicaloperationalplanitems',
            name='evidence_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ طلب الدليل'),
        ),
        migrations.AddField(
            model_name='operationalplanitems',
            name='evidence_request_note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظة طلب الدليل'),
        ),
        migrations.AddField(
            model_name='operationalplanitems',
            name='evidence_requested',
            field=models.BooleanField(default=False, verbose_name='طلب دليل؟'),
        ),
        migrations.AddField(
            model_name='operationalplanitems',
            name='evidence_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ طلب الدليل'),
        ),
        migrations.AlterField(
            model_name='historicaloperationalplanitems',
            name='evidence_source_file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='موقع الدليل (نصي)'),
        ),
        migrations.AlterField(
            model_name='operationalplanitems',
            name='evidence_source_file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='موقع الدليل (نصي)'),
        ),
    ]
