# Generated by Django 6.0.2 on 2026-02-09 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('coredata', '0016_alter_historicalevidencefile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis1_evaluators', models.ManyToManyField(blank=True, related_name='axis1_groups', to=settings.AUTH_USER_MODEL, verbose_name='مقيّمين محور 1')),
                ('axis2_evaluators', models.ManyToManyField(blank=True, related_name='axis2_groups', to=settings.AUTH_USER_MODEL, verbose_name='مقيّمين محور 2')),
                ('axis3_evaluators', models.ManyToManyField(blank=True, related_name='axis3_groups', to=settings.AUTH_USER_MODEL, verbose_name='مقيّمين محور 3')),
                ('axis4_evaluators', models.ManyToManyField(blank=True, related_name='axis4_groups', to=settings.AUTH_USER_MODEL, verbose_name='مقيّمين محور 4')),
                ('axis5_evaluators', models.ManyToManyField(blank=True, related_name='axis5_groups', to=settings.AUTH_USER_MODEL, verbose_name='مقيّمين محور 5')),
                ('axis6_evaluators', models.ManyToManyField(blank=True, related_name='axis6_groups', to=settings.AUTH_USER_MODEL, verbose_name='مقيّمين محور 6')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='auth.group')),
            ],
        ),
    ]
