# Generated by Django 6.0.2 on 2026-02-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0017_groupextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupextension',
            name='axis1_name',
            field=models.CharField(blank=True, default='المحور الأول', max_length=255, verbose_name='اسم المحور 1'),
        ),
        migrations.AddField(
            model_name='groupextension',
            name='axis2_name',
            field=models.CharField(blank=True, default='المحور الثاني', max_length=255, verbose_name='اسم المحور 2'),
        ),
        migrations.AddField(
            model_name='groupextension',
            name='axis3_name',
            field=models.CharField(blank=True, default='المحور الثالث', max_length=255, verbose_name='اسم المحور 3'),
        ),
        migrations.AddField(
            model_name='groupextension',
            name='axis4_name',
            field=models.CharField(blank=True, default='المحور الرابع', max_length=255, verbose_name='اسم المحور 4'),
        ),
        migrations.AddField(
            model_name='groupextension',
            name='axis5_name',
            field=models.CharField(blank=True, default='المحور الخامس', max_length=255, verbose_name='اسم المحور 5'),
        ),
        migrations.AddField(
            model_name='groupextension',
            name='axis6_name',
            field=models.CharField(blank=True, default='المحور السادس', max_length=255, verbose_name='اسم المحور 6'),
        ),
    ]
