# Generated by Django 6.0.2 on 2026-02-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('coredata', '0018_groupextension_axis1_name_groupextension_axis2_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljobtitle',
            name='is_canonical',
            field=models.BooleanField(default=False, verbose_name='مسمى معتمد/رئيسي'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='المجموعات التي سينضم إليها الموظف تلقائياً عند حمله لهذا المسمى', related_name='job_titles', to='auth.group', verbose_name='مجموعات الصلاحيات (Django Groups)'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='is_canonical',
            field=models.BooleanField(default=False, verbose_name='مسمى معتمد/رئيسي'),
        ),
    ]
