# Generated by Django 5.2.10 on 2026-02-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitecturalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adr_id', models.CharField(max_length=10, unique=True, verbose_name='رقم القرار')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('منفذ', 'منفذ'), ('مقترح', 'مقترح'), ('ملغي', 'ملغي')], default='مقترح', max_length=50, verbose_name='الحالة')),
                ('context', models.TextField(help_text='ما هي المشكلة أو السياق الذي أدى إلى هذا القرار؟', verbose_name='السياق')),
                ('decision', models.TextField(help_text='ما هو القرار التقني الذي تم اتخاذه؟', verbose_name='القرار')),
                ('justification', models.TextField(help_text='لماذا تم اتخاذ هذا القرار؟ ما هي البدائل التي تم النظر فيها؟', verbose_name='المبررات')),
            ],
            options={
                'verbose_name': 'قرار معماري',
                'verbose_name_plural': 'سجل القرارات المعمارية',
                'ordering': ['-date', '-adr_id'],
            },
        ),
    ]
