# Generated by Django 5.2.10 on 2026-02-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_memory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidingPrinciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='المبدأ')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('principle_type', models.CharField(choices=[('هندسي', 'هندسي'), ('حوكمة', 'حوكمة')], max_length=50, verbose_name='نوع المبدأ')),
            ],
            options={
                'verbose_name': 'مبدأ توجيهي',
                'verbose_name_plural': 'المبادئ والحوكمة',
            },
        ),
        migrations.CreateModel(
            name='ProjectGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='الهدف')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('goal_type', models.CharField(choices=[('استراتيجي', 'استراتيجي'), ('قصير المدى', 'قصير المدى'), ('ميزة مستقبلية', 'ميزة مستقبلية')], max_length=50, verbose_name='نوع الهدف')),
                ('kpi', models.CharField(blank=True, max_length=255, null=True, verbose_name='مؤشر الأداء الرئيسي (KPI)')),
                ('measurement', models.CharField(blank=True, max_length=255, null=True, verbose_name='كيفية القياس')),
            ],
            options={
                'verbose_name': 'هدف المشروع',
                'verbose_name_plural': 'أهداف المشروع',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='التقنية')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='الإصدار')),
                ('layer', models.CharField(max_length=100, verbose_name='الطبقة')),
                ('purpose', models.TextField(verbose_name='سبب الاختيار')),
            ],
            options={
                'verbose_name': 'تقنية مستخدمة',
                'verbose_name_plural': 'المكدس التقني',
            },
        ),
    ]
