# Generated by Django 5.2.10 on 2026-02-04 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_memory', '0002_guidingprinciple_projectgoal_technology'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التوقيت')),
                ('event_type', models.CharField(choices=[('CODE_CHANGE', 'تغيير في الكود'), ('MIGRATION', 'تطبيق هجرة'), ('DEPENDENCY', 'تغيير في المكتبات'), ('ADMIN_ACTION', 'إجراء إداري'), ('USER_COMMENT', 'تعليق مستخدم')], max_length=20, verbose_name='نوع الحدث')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='تفاصيل')),
                ('is_significant', models.BooleanField(default=False, help_text='هل يجب أن يتحول هذا الحدث إلى قرار معماري (ADR)؟', verbose_name='حدث هام؟')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرتبط')),
            ],
            options={
                'verbose_name': 'حدث في الذاكرة',
                'verbose_name_plural': 'سجل أحداث الذاكرة',
                'ordering': ['-timestamp'],
            },
        ),
    ]
