# Generated by Django 6.0.2 on 2026-02-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_memory', '0003_memoryevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwotAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('STRENGTH', 'نقطة قوة'), ('WEAKNESS', 'نقطة ضعف'), ('OPPORTUNITY', 'فرصة'), ('THREAT', 'تهديد')], max_length=20, verbose_name='التصنيف')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عنصر SWOT',
                'verbose_name_plural': 'تحليل SWOT',
            },
        ),
        migrations.CreateModel(
            name='ActionPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='الإجراء')),
                ('description', models.TextField(blank=True, null=True, verbose_name='التفاصيل')),
                ('priority', models.CharField(choices=[('HIGH', 'عالية'), ('MEDIUM', 'متوسطة'), ('LOW', 'منخفضة')], default='MEDIUM', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('IN_PROGRESS', 'جاري التنفيذ'), ('DONE', 'مكتمل')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_swot', models.ManyToManyField(blank=True, to='project_memory.swotanalysis', verbose_name='مرتبط بـ SWOT')),
            ],
            options={
                'verbose_name': 'إجراء تنفيذي',
                'verbose_name_plural': 'خطة العمل',
            },
        ),
    ]
