# Generated by Django 6.0.2 on 2026-02-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_memory', '0004_swotanalysis_actionplanitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplanitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='projectgoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projectgoal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='swotanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionplanitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionplanitem',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'عالية'), ('MEDIUM', 'متوسطة'), ('LOW', 'منخفضة')], db_index=True, default='MEDIUM', max_length=10, verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='actionplanitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('IN_PROGRESS', 'جاري التنفيذ'), ('DONE', 'مكتمل')], db_index=True, default='PENDING', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='actionplanitem',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='الإجراء'),
        ),
        migrations.AlterField(
            model_name='projectgoal',
            name='goal_type',
            field=models.CharField(choices=[('استراتيجي', 'استراتيجي'), ('قصير المدى', 'قصير المدى'), ('ميزة مستقبلية', 'ميزة مستقبلية')], db_index=True, max_length=50, verbose_name='نوع الهدف'),
        ),
        migrations.AlterField(
            model_name='projectgoal',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='الهدف'),
        ),
        migrations.AlterField(
            model_name='swotanalysis',
            name='category',
            field=models.CharField(choices=[('STRENGTH', 'نقطة قوة'), ('WEAKNESS', 'نقطة ضعف'), ('OPPORTUNITY', 'فرصة'), ('THREAT', 'تهديد')], db_index=True, max_length=20, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='swotanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='swotanalysis',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='layer',
            field=models.CharField(db_index=True, max_length=100, verbose_name='الطبقة'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='التقنية'),
        ),
    ]
