# Generated by Django 6.0.2 on 2026-02-07 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_memory', '0005_actionplanitem_updated_at_projectgoal_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionplanitem',
            options={'ordering': ['-importance_score', '-priority'], 'verbose_name': 'إجراء تنفيذي', 'verbose_name_plural': 'خطة العمل'},
        ),
        migrations.AddField(
            model_name='actionplanitem',
            name='complexity',
            field=models.CharField(choices=[('SIMPLE', 'بسيط'), ('MEDIUM', 'متوسط'), ('COMPLEX', 'مركب')], default='MEDIUM', max_length=20, verbose_name='التعقيد'),
        ),
        migrations.AddField(
            model_name='actionplanitem',
            name='estimated_duration_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, max_length=10, verbose_name='المدة التقديرية (ساعة)'),
        ),
        migrations.AddField(
            model_name='actionplanitem',
            name='impact',
            field=models.IntegerField(default=5, verbose_name='الأثر الاستراتيجي (1-10)'),
        ),
        migrations.AddField(
            model_name='actionplanitem',
            name='importance_score',
            field=models.IntegerField(default=0, editable=False, verbose_name='مؤشر الأهمية'),
        ),
        migrations.AddField(
            model_name='actionplanitem',
            name='planned_start',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البدء المخطط'),
        ),
        migrations.AddField(
            model_name='actionplanitem',
            name='related_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='project_memory.projectgoal', verbose_name='الهدف المرتبط'),
        ),
        migrations.AddField(
            model_name='actionplanitem',
            name='urgency',
            field=models.IntegerField(default=5, verbose_name='درجة الاستعجال (1-10)'),
        ),
    ]
